import { randomBytes } from 'node:crypto'
import { createAdminClient } from '@/lib/supabase/admin'
import { writeAuditEvent } from '@/lib/accounts/audit'
import { requireAutomationAccess, automationAccessResponse } from '@/lib/platform/auth/automationsContext'
import { WEBHOOK_EVENT_SET } from '@/lib/platform/events/eventTypes'
import { encryptWebhookSecret } from '@/lib/platform/webhooks/crypto'
import { validateWebhookUrl } from '@/lib/platform/webhooks/delivery'
export const dynamic='force-dynamic'
export async function GET(request:Request){ try{ const storeId=new URL(request.url).searchParams.get('storeId')??''; const actor=await requireAutomationAccess(storeId,'webhooks.manage'); const {data,error}=await createAdminClient().from('balcao_webhook_endpoints').select('id,name,url,event_types,status,consecutive_failures,last_success_at,last_failure_at,created_at').eq('business_id',actor.businessId).eq('store_id',storeId).order('created_at',{ascending:false}); if(error) throw error; return Response.json({webhooks:data??[]}) }catch(error){ return automationAccessResponse(error) } }
export async function POST(request:Request){ try{ const body=await request.json(); const storeId=String(body.storeId??''); const actor=await requireAutomationAccess(storeId,'webhooks.manage'); const name=String(body.name??'').trim(); const url=String(body.url??'').trim(); const events=Array.isArray(body.eventTypes)?[...new Set(body.eventTypes.filter((event:unknown)=>typeof event==='string'&&WEBHOOK_EVENT_SET.has(event)))]:[]; if(name.length<2||!validateWebhookUrl(url)||!events.length) return Response.json({error:'Informe nome, URL HTTPS pública e pelo menos um evento válido.'},{status:400}); const secret=`whsec_${randomBytes(32).toString('base64url')}`; const {data,error}=await createAdminClient().from('balcao_webhook_endpoints').insert({business_id:actor.businessId,store_id:storeId,name,url,event_types:events,secret_ciphertext:encryptWebhookSecret(secret),status:'active',created_by_user_id:actor.actorUserId,created_by_staff_id:actor.actorStaffId}).select('id').single(); if(error) throw error; await writeAuditEvent({businessId:actor.businessId,storeId,actorUserId:actor.actorUserId,actorStaffId:actor.actorStaffId,action:'webhook.created',entityType:'webhook',entityId:String(data.id),metadata:{url,eventTypes:events}}); return Response.json({id:data.id,secret},{status:201}) }catch(error){ return automationAccessResponse(error) } }
