import { createInventoryCloudClient } from '@/lib/supabase/inventoryCloud'
import { loadInventoryState, saveInventoryState, type PlatformInventoryState } from '@/lib/platform/inventoryAdapter'
import type { AutomationActor } from '@/lib/platform/auth/automationsContext'
import { AUTOMATION_RECIPES, getAutomationRecipe, type AutomationMode, type AutomationRecipeKey } from './recipes'
import { evaluateRecipe, simulateRecipe, type AutomationFinding } from './engine'

type PersistedAutomation={id:string;recipe_key:AutomationRecipeKey;name:string;status:'active'|'paused';mode:AutomationMode;config:Record<string,unknown>;scope:Record<string,unknown>;last_run_at?:string|null;created_at:string;updated_at:string}
type CenterState={automations:PersistedAutomation[];runs:any[];actions:any[]}
const cloud=()=>createInventoryCloudClient()
async function persisted(actor:AutomationActor):Promise<CenterState>{const{data,error}=await cloud().rpc('balcao_automation_center_state',{p_store_id:actor.storeId,p_installation_id:actor.installationId});if(error)throw error;const value=(data??{}) as any;return{automations:Array.isArray(value.automations)?value.automations:[],runs:Array.isArray(value.runs)?value.runs:[],actions:Array.isArray(value.actions)?value.actions:[]}}
function configFor(item:PersistedAutomation|undefined,key:AutomationRecipeKey){const recipe=getAutomationRecipe(key)!;return{...recipe.defaultConfig,...(item?.config??{})}}
export async function getAutomationCenter(actor:AutomationActor){const[state,inventory]=await Promise.all([persisted(actor),loadInventoryState(actor.storeId,actor.businessId,actor.installationId)]);const byKey=new Map(state.automations.map(a=>[a.recipe_key,a]));const catalogue=AUTOMATION_RECIPES.map(recipe=>{const automation=byKey.get(recipe.key),config=configFor(automation,recipe.key),simulation=simulateRecipe(recipe.key,inventory,config);return{...recipe,automation,simulation}});const suggestions=catalogue.filter(x=>!x.automation&&x.simulation.matches>0).sort((a,b)=>b.simulation.critical-a.simulation.critical||b.simulation.matches-a.simulation.matches).slice(0,8);const active=state.automations.filter(a=>a.status==='active');const activeFindings=active.flatMap(a=>evaluateRecipe(a.recipe_key,inventory,configFor(a,a.recipe_key)));const today=new Date();today.setHours(0,0,0,0);const runsToday=state.runs.filter(r=>new Date(r.started_at).getTime()>=today.getTime()).length;return{overview:{activeAutomations:active.length,runsToday,attention:activeFindings.filter(f=>f.severity!=='info').length,openFindings:activeFindings.length},automations:state.automations,catalogue,suggestions,runs:state.runs,actions:state.actions,activeFindings:activeFindings.slice(0,100)}}
export async function upsertAutomation(actor:AutomationActor,input:{recipeKey:string;status?:string;mode?:string;config?:Record<string,unknown>;scope?:Record<string,unknown>}){const recipe=getAutomationRecipe(input.recipeKey);if(!recipe)throw new Error('BALCAO_AUTOMATION_RECIPE_NOT_FOUND');const status=input.status==='paused'?'paused':'active',mode=(['notify','recommend','automatic'].includes(String(input.mode))?input.mode:recipe.defaultMode) as AutomationMode;if(mode==='automatic'&&!recipe.supportsAutomatic)throw new Error('BALCAO_AUTOMATION_MODE_NOT_SUPPORTED');const config={...recipe.defaultConfig,...(input.config??{})};const{data,error}=await cloud().rpc('balcao_automation_upsert',{p_store_id:actor.storeId,p_installation_id:actor.installationId,p_recipe_key:recipe.key,p_name:recipe.title,p_status:status,p_mode:mode,p_config:config,p_scope:input.scope??{type:'all'}});if(error)throw error;return data}
function recentPriceChange(actions:any[],automationId:string,productId:string,days:number){const cutoff=Date.now()-days*86_400_000;return actions.some(a=>String(a.automation_id)===automationId&&a.action_type==='price_change'&&String(a.entity_id)===productId&&new Date(a.created_at).getTime()>=cutoff&&a.status==='applied')}
function buildAction(finding:AutomationFinding,status='observed'){return{entityType:finding.entityType??'store',entityId:finding.entityId??'store',entityName:finding.entityName??'Loja',actionType:finding.recommendation?'recommendation':'finding',status,severity:finding.severity,title:finding.title,description:finding.description,beforeState:{},afterState:{},metadata:{...finding.metrics,recommendation:finding.recommendation??null},rollbackAvailable:false}}
export async function runAutomation(actor:AutomationActor,automationId:string){const[state,inventory]=await Promise.all([persisted(actor),loadInventoryState(actor.storeId,actor.businessId,actor.installationId)]);const automation=state.automations.find(a=>a.id===automationId);if(!automation)throw new Error('BALCAO_AUTOMATION_NOT_FOUND');const config=configFor(automation,automation.recipe_key),findings=evaluateRecipe(automation.recipe_key,inventory,config),actions=findings.map(f=>buildAction(f));let mutated=false;const next:PlatformInventoryState={...inventory,products:inventory.products.map(p=>({...p}))};if(automation.mode==='automatic'&&(automation.recipe_key==='smart_pricing'||automation.recipe_key==='margin_protection')){const interval=Number(config.minimumIntervalDays??7);for(let i=0;i<findings.length;i++){const finding=findings[i],rec=finding.recommendation;if(!rec?.recommendedPriceCents||!finding.entityId)continue;if(automation.recipe_key==='smart_pricing'&&rec.confidence==='low')continue;if(recentPriceChange(state.actions,automation.id,finding.entityId,interval))continue;const index=next.products.findIndex((p:any)=>String(p.id)===finding.entityId);if(index<0)continue;const oldPrice=Number((next.products[index] as any).priceCents??0),newPrice=Math.round(rec.recommendedPriceCents);if(oldPrice===newPrice)continue;(next.products[index] as any).priceCents=newPrice;actions[i]={...actions[i],actionType:'price_change',status:'applied',beforeState:{priceCents:oldPrice},afterState:{priceCents:newPrice},rollbackAvailable:true};mutated=true}}
if(mutated)await saveInventoryState(actor.storeId,actor.businessId,next,actor.installationId);const summary={recipeKey:automation.recipe_key,matched:findings.length,applied:actions.filter(a=>a.status==='applied').length};const{data,error}=await cloud().rpc('balcao_automation_record_run',{p_store_id:actor.storeId,p_installation_id:actor.installationId,p_automation_id:automation.id,p_status:'success',p_trigger:'manual_or_state',p_summary:summary,p_actions:actions});if(error)throw error;return{runId:data,summary,findings,actions}}
