import { createAdminClient } from '@/lib/supabase/admin'
import { loadInventoryState, saveInventoryState } from '../inventoryAdapter'
import type { PricingRecommendation, PricingReason } from '../contracts/pricing'
import { emitPlatformEvent } from '../events/outbox'
function psychological(cents:number){ if(cents<=100)return Math.max(1,cents); return Math.max(1,Math.ceil(cents/10)*10-1) }
function margin(price:number,cost:number){ return price>0?(price-cost)*100/price:0 }
export async function pricingRecommendations(storeId:string,businessId:string):Promise<PricingRecommendation[]>{ const state=await loadInventoryState(storeId,businessId); const cutoff=Date.now()-30*86400000; const sold=new Map<string,number>(); for(const sale of state.sales){if(new Date(sale.createdAt).getTime()<cutoff)continue;for(const item of sale.items??[])sold.set(String(item.productId),(sold.get(String(item.productId))??0)+Number(item.quantityMilli??0))} return state.products.filter((p:any)=>!p.deletedAt&&Number(p.priceCents)>0).map((p:any)=>{const price=Math.round(Number(p.priceCents??0)),cost=Math.max(0,Math.round(Number(p.averageCostCents??0))),soldMilli=sold.get(String(p.id))??0,unitsSold30d=soldMilli/1000,daily=unitsSold30d/30,days=daily>0?Number(p.stockMilli??0)/1000/daily:null,currentMargin=margin(price,cost);const reasons:PricingReason[]=[];let raw=price;if(cost>0&&currentMargin<25){raw=Math.max(raw,cost/(1-.30));reasons.push('margin_low')}if(days!==null&&days<7&&unitsSold30d>=10&&currentMargin<45){raw=Math.max(raw,price*1.03);reasons.push('high_demand')}if(days!==null&&days>60&&currentMargin>35){raw=Math.min(raw,price*.97);reasons.push('slow_stock')}if(!reasons.length)reasons.push('healthy');const minPrice=cost>0?cost/(1-.25):1,lower=Math.max(minPrice,price*.95),upper=price*1.05,recommended=psychological(Math.round(Math.max(lower,Math.min(upper,raw)))),confidence:'low'|'medium'|'high'=unitsSold30d>=60?'high':unitsSold30d>=20?'medium':'low',action:PricingRecommendation['action']=recommended>price?'raise':recommended<price?'lower':'keep';return{productId:String(p.id),productName:String(p.name??''),currentPriceCents:price,recommendedPriceCents:recommended,costCents:cost,grossMarginPct:Math.round(currentMargin*100)/100,expectedGrossMarginPct:Math.round(margin(recommended,cost)*100)/100,daysOfInventory:days===null?null:Math.round(days*10)/10,unitsSold30d:Math.round(unitsSold30d*1000)/1000,confidence,reasons,action}}).sort((a,b)=>Math.abs(b.recommendedPriceCents-b.currentPriceCents)-Math.abs(a.recommendedPriceCents-a.currentPriceCents)) }
export async function pricingHistory(storeId:string,businessId:string){const {data,error}=await createAdminClient().from('balcao_pricing_history').select('id,product_id,old_price_cents,new_price_cents,source,reason,created_at').eq('business_id',businessId).eq('store_id',storeId).order('created_at',{ascending:false}).limit(250);if(error)throw error;return data??[]}
export async function pricingSettings(storeId:string,businessId:string){const admin=createAdminClient();const {data,error}=await admin.from('balcao_pricing_settings').select('*').eq('store_id',storeId).eq('business_id',businessId).maybeSingle();if(error)throw error;return data??{store_id:storeId,business_id:businessId,mode:'recommend',minimum_margin_bps:2500,target_margin_bps:3000,max_change_bps:500,minimum_interval_days:7,minimum_sales_count:20}}
export async function savePricingSettings(input:{storeId:string;businessId:string;mode:'off'|'recommend'|'automatic';minimumMarginBps:number;targetMarginBps:number;maxChangeBps:number;minimumIntervalDays:number;minimumSalesCount:number;actorUserId?:string|null;actorStaffId?:string|null}){const row={store_id:input.storeId,business_id:input.businessId,mode:input.mode,minimum_margin_bps:input.minimumMarginBps,target_margin_bps:input.targetMarginBps,max_change_bps:input.maxChangeBps,minimum_interval_days:input.minimumIntervalDays,minimum_sales_count:input.minimumSalesCount,updated_by_user_id:input.actorUserId??null,updated_by_staff_id:input.actorStaffId??null,updated_at:new Date().toISOString()};const{error}=await createAdminClient().from('balcao_pricing_settings').upsert(row,{onConflict:'store_id'});if(error)throw error;return row}
export async function applyRecommendedPrice(input:{storeId:string;businessId:string;productId:string;source:'recommendation'|'automatic'|'api';actorUserId?:string|null;actorStaffId?:string|null}){const recommendation=(await pricingRecommendations(input.storeId,input.businessId)).find((r)=>r.productId===input.productId);if(!recommendation)throw new Error('BALCAO_PRICING_NOT_FOUND');if(recommendation.action==='keep')return recommendation;const state=await loadInventoryState(input.storeId,input.businessId);const index=state.products.findIndex((p:any)=>String(p.id)===input.productId);if(index<0)throw new Error('BALCAO_PRICING_NOT_FOUND');const oldPrice=Number(state.products[index].priceCents??0);state.products[index]={...state.products[index],priceCents:recommendation.recommendedPriceCents};await saveInventoryState(input.storeId,input.businessId,state);const admin=createAdminClient();await admin.from('balcao_pricing_history').insert({business_id:input.businessId,store_id:input.storeId,product_id:input.productId,old_price_cents:oldPrice,new_price_cents:recommendation.recommendedPriceCents,source:input.source,reason:recommendation.reasons,actor_user_id:input.actorUserId??null,actor_staff_id:input.actorStaffId??null});await emitPlatformEvent({businessId:input.businessId,storeId:input.storeId,type:'pricing.price.changed',aggregateType:'product',aggregateId:input.productId,data:{productId:input.productId,oldPriceCents:oldPrice,newPriceCents:recommendation.recommendedPriceCents,source:input.source,reasons:recommendation.reasons}});return recommendation}
