const RAW_BRANDS = [
  "omo",
  "ype",
  "italac",
  "ninho",
  "moca",
  "nestle",
  "sadia",
  "perdigao",
  "seara",
  "camil",
  "tio joao",
  "kicaldo",
  "uniao",
  "liza",
  "soya",
  "barilla",
  "renata",
  "heinz",
  "pomarola",
  "dona benta",
  "cisne",
  "qualy",
  "presidente",
  "pullman",
  "wickbold",
  "coca cola",
  "guarana antarctica",
  "brahma",
  "skol",
  "heineken",
  "crystal",
  "neve",
  "personal",
  "oreo",
  "passatempo",
  "bauducco",
  "3 coracoes",
  "pilao",
  "melitta",
  "granja brasil",
  "adria",
  "vitarella",
  "piraque",
  "marilan",
  "trakinas",
  "club social",
  "toddy",
  "nescau",
  "tang",
  "mid",
  "del valle",
  "fanta",
  "sprite",
  "schweppes",
  "pepsi",
  "sukita",
  "h2oh",
  "kuat",
  "antarctica",
  "bohemia",
  "stella artois",
  "budweiser",
  "corona",
  "itaipava",
  "petra",
  "original",
  "serramalte",
  "eisenbahn",
  "spaten",
  "bavaria",
  "devassa",
  "minalba",
  "bonafont",
  "indaia",
  "lindoia",
  "prata",
  "sao lourenco",
  "leao",
  "matte leao",
  "tial",
  "do bem",
  "ades",
  "piracanjuba",
  "parmalat",
  "elege",
  "batavo",
  "vigor",
  "danone",
  "activia",
  "actimel",
  "yakult",
  "tirol",
  "aurora",
  "frimesa",
  "scala",
  "polenghi",
  "catupiry",
  "itambe",
  "camponesa",
  "aviacao",
  "becel",
  "doriana",
  "delicia",
  "claybom",
  "primor",
  "salsaretti",
  "quero",
  "predilecta",
  "fugini",
  "elefante",
  "cepera",
  "knorr",
  "maggi",
  "hellmanns",
  "arisco",
  "sazon",
  "ajinomoto",
  "kitano",
  "zaeli",
  "yoki",
  "mae terra",
  "jasmine",
  "native",
  "vitao",
  "urbano",
  "prato fino",
  "namorado",
  "broto legal",
  "codil",
  "caldo bom",
  "combrasil",
  "gallo",
  "andorinha",
  "carbonell",
  "borges",
  "salada",
  "coamo",
  "cocamar",
  "sinha",
  "quaker",
  "kelloggs",
  "sucrilhos",
  "nutella",
  "ferrero",
  "kinder",
  "lacta",
  "garoto",
  "hersheys",
  "neugebauer",
  "arcor",
  "fini",
  "mentos",
  "halls",
  "trident",
  "bis",
  "sonho de valsa",
  "ouro branco",
  "alpino",
  "talento",
  "prestigio",
  "toddynho",
  "mucilon",
  "nesfit",
  "nescafe",
  "nespresso",
  "caboclo",
  "brasileiro",
  "vapza",
  "sakura",
  "hinomoto",
  "kikkoman",
  "marata",
  "lebon",
  "minuano",
  "brilhante",
  "tixan",
  "surf",
  "ace",
  "ariel",
  "comfort",
  "downy",
  "fofo",
  "mon bijou",
  "vanish",
  "veja",
  "mr musculo",
  "pinho sol",
  "ajax",
  "assolan",
  "bombril",
  "scotch brite",
  "esfrebom",
  "limpol",
  "coala",
  "sanol",
  "harpic",
  "lysoform",
  "sbp",
  "raid",
  "off",
  "johnson",
  "granado",
  "phebo",
  "protex",
  "dove",
  "lux",
  "rexona",
  "nivea",
  "palmolive",
  "seda",
  "pantene",
  "clear",
  "elseve",
  "tresemme",
  "colgate",
  "oral b",
  "sorriso",
  "closeup",
  "sensodyne",
  "gillette",
  "bic",
  "always",
  "intimus",
  "carefree",
  "babysec",
  "pom pom",
  "huggies",
  "pampers",
  "mili",
  "capricho",
  "elite",
  "snob",
  "scott",
]

function normalize(value: string) {
  return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/0/g, 'o').replace(/[^a-z0-9]+/g, ' ').trim()
}

export const RETAIL_BRANDS = [...new Set(RAW_BRANDS.map(normalize).filter(Boolean))]

function levenshtein(a: string, b: string) {
  const prev = Array.from({ length: b.length + 1 }, (_, i) => i)
  for (let i = 1; i <= a.length; i++) {
    let diagonal = prev[0]
    prev[0] = i
    for (let j = 1; j <= b.length; j++) {
      const old = prev[j]
      prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, diagonal + (a[i - 1] === b[j - 1] ? 0 : 1))
      diagonal = old
    }
  }
  return prev[b.length]
}

export function detectBrand(description: string): string | null {
  const text = normalize(description)
  if (!text) return null
  const tokens = text.split(' ')
  const ordered = [...RETAIL_BRANDS].sort((a, b) => b.length - a.length)
  for (const brand of ordered) {
    const brandTokens = brand.split(' ')
    for (let i = 0; i <= tokens.length - brandTokens.length; i++) {
      const sample = tokens.slice(i, i + brandTokens.length)
      let ok = true
      for (let j = 0; j < brandTokens.length; j++) {
        const expected = brandTokens[j]
        const actual = sample[j]
        if (actual === expected) continue
        if (expected.length >= 4 && actual.length >= 3 && levenshtein(actual, expected) <= 1) continue
        ok = false
        break
      }
      if (ok) return brand
    }
  }
  return null
}
