'use client'

import { useEffect,useMemo,useState } from 'react'
import { Activity, Bot, CheckCircle2, ChevronRight, Clock3, History, KeyRound, Lightbulb, LoaderCircle, Pause, Play, Settings2, ShieldCheck, Sparkles, Store, Wrench } from 'lucide-react'
import ApiKeysPanel from './automations/ApiKeysPanel'
import IntegrationsPanel from './automations/IntegrationsPanel'
import WebhooksPanel from './automations/WebhooksPanel'
import IntegrationLogsPanel from './automations/IntegrationLogsPanel'
import ExportsPanel from './automations/ExportsPanel'
import AutomationError from './automations/AutomationError'
import { automationRequest, AutomationClientError } from '@/lib/platform/automation/client'

type View='overview'|'mine'|'discover'|'suggestions'|'history'|'technical'
type Center=any
const nav:[View,string,any][]=[['overview','Visão geral',Activity],['mine','Minhas automações',Bot],['discover','Descobrir',Sparkles],['suggestions','Sugestões',Lightbulb],['history','Histórico',History],['technical','Integrações e API',KeyRound]]
const categoryLabel:Record<string,string>={pricing:'Preços e margem',inventory:'Estoque',sales:'Vendas',finance:'Financeiro'}
const modeLabel:Record<string,string>={notify:'Só me avise',recommend:'Recomendar',automatic:'Automático'}
const configLabels:Record<string,string>={minimumMarginPct:'Margem mínima (%)',targetMarginPct:'Margem desejada (%)',maxChangePct:'Mudança máxima por vez (%)',minimumIntervalDays:'Intervalo mínimo (dias)',minimumSalesCount:'Mínimo de vendas em 30 dias',stockoutDays:'Risco de ruptura (dias)',excessDays:'Estoque excessivo (dias)',days:'Limite de dias',minimumSales30d:'Mínimo de vendas em 30 dias',maxSales30d:'Máximo de vendas em 30 dias',minimumStockUnits:'Estoque mínimo para analisar',reorderAtDays:'Repor quando restarem (dias)',targetDays:'Cobertura desejada (dias)',dropPct:'Queda para alertar (%)',minimumPreviousRevenueCents:'Receita mínima anterior (centavos)',increasePct:'Aumento fora do normal (%)'}
function time(value?:string|null){if(!value)return'Nunca';return new Date(value).toLocaleString('pt-BR')}
function statusClass(status:string){return status==='active'?'bg-emerald-50 text-emerald-800':'bg-slate-100 text-slate-600'}

export default function AutomationsHub({storeId,managementAccess=false}:{storeId:string;managementAccess?:boolean}){
 const[view,setView]=useState<View>('overview'),[center,setCenter]=useState<Center|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState<{message:string;code:string}|null>(null),[selected,setSelected]=useState<any|null>(null),[draftMode,setDraftMode]=useState('recommend'),[draftConfig,setDraftConfig]=useState<Record<string,any>>({})
 async function load(){setLoading(true);setError(null);try{setCenter(await automationRequest(`/api/balcao/automations/center?storeId=${encodeURIComponent(storeId)}`,undefined,'AUT-LOAD-001'))}catch(e){const x=e as AutomationClientError;setError({message:x.message,code:x.code||'AUT-LOAD-001'})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[storeId])
 const automationByRecipe=useMemo(()=>new Map((center?.automations??[]).map((a:any)=>[a.recipe_key,a])),[center])
 function openRecipe(item:any){const automation=automationByRecipe.get(item.key) as any;setSelected(item);setDraftMode(automation?.mode??item.defaultMode);setDraftConfig({...item.defaultConfig,...(automation?.config??{})})}
 async function saveRecipe(item:any,status='active'){setBusy(`save:${item.key}`);setError(null);try{await automationRequest('/api/balcao/automations/center',{method:'POST',body:JSON.stringify({storeId,recipeKey:item.key,status,mode:draftMode,config:draftConfig,scope:{type:'all'}})},'AUT-SAVE-001');setSelected(null);await load()}catch(e){const x=e as AutomationClientError;setError({message:x.message,code:x.code||'AUT-SAVE-001'})}finally{setBusy('')}}
 async function toggle(automation:any){const item=(center?.catalogue??[]).find((x:any)=>x.key===automation.recipe_key);if(!item)return;setDraftMode(automation.mode);setDraftConfig(automation.config??{});setBusy(`toggle:${automation.id}`);try{await automationRequest('/api/balcao/automations/center',{method:'POST',body:JSON.stringify({storeId,recipeKey:automation.recipe_key,status:automation.status==='active'?'paused':'active',mode:automation.mode,config:automation.config,scope:automation.scope})},'AUT-TOGGLE-001');await load()}catch(e){const x=e as AutomationClientError;setError({message:x.message,code:x.code})}finally{setBusy('')}}
 async function run(automation:any){setBusy(`run:${automation.id}`);setError(null);try{await automationRequest(`/api/balcao/automations/center/${automation.id}/run`,{method:'POST',body:JSON.stringify({storeId})},'AUT-RUN-001');await load()}catch(e){const x=e as AutomationClientError;setError({message:x.message,code:x.code})}finally{setBusy('')}}
 if(loading&&!center)return <div className="flex min-h-64 items-center justify-center gap-2 text-slate-500"><LoaderCircle className="h-5 w-5 animate-spin"/>Preparando suas automações…</div>
 if(!center&&error)return <AutomationError message={error.message} code={error.code} onRetry={()=>void load()}/>
 const o=center?.overview??{activeAutomations:0,runsToday:0,attention:0,openFindings:0}
 return <div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]">
  <aside className="h-fit rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="px-3 py-3"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">Automações</p><p className="mt-1 text-sm text-slate-500">O BALCÃO trabalhando por você.</p></div><nav className="grid gap-1">{nav.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setView(id)} className={`flex min-h-11 items-center gap-3 rounded-xl px-3 text-left text-sm font-bold ${view===id?'bg-blue-700 text-white':'text-slate-700 hover:bg-slate-100'}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>{managementAccess?<p className="mt-3 border-t px-3 pt-3 text-[11px] text-slate-400">Acesso de gestão</p>:null}</aside>
  <main className="min-w-0 space-y-5">{error?<AutomationError message={error.message} code={error.code} onRetry={()=>void load()}/>:null}
   {view==='overview'?<><section className="overflow-hidden rounded-3xl bg-slate-950 p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-300">Central de automações</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Cuide menos de tarefas repetitivas.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">O BALCÃO acompanha estoque, margem e vendas, encontra o que merece atenção e registra tudo que fez.</p></div><button onClick={()=>setView('discover')} className="min-h-11 rounded-xl bg-white px-4 text-sm font-black text-slate-950">Descobrir automações</button></div></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[o.activeAutomations,'Automações ativas',Bot],[o.runsToday,'Executadas hoje',Play],[o.attention,'Precisam de atenção',ShieldCheck],[o.openFindings,'Oportunidades abertas',Lightbulb]].map(([value,label,Icon]:any)=><div key={label} className="rounded-2xl border bg-white p-5"><Icon className="h-5 w-5 text-blue-700"/><strong className="mt-4 block text-3xl">{value}</strong><span className="mt-1 block text-sm text-slate-500">{label}</span></div>)}</section><section className="grid gap-4 xl:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><div><h2 className="font-black">Sugestões do BALCÃO</h2><p className="text-sm text-slate-500">Com base nos seus dados atuais.</p></div><button onClick={()=>setView('suggestions')} className="text-sm font-bold text-blue-700">Ver todas</button></div><div className="mt-4 grid gap-2">{(center.suggestions??[]).slice(0,4).map((x:any)=><button key={x.key} onClick={()=>openRecipe(x)} className="flex items-center justify-between rounded-xl border p-3 text-left"><span><b>{x.title}</b><span className="block text-xs text-slate-500">{x.simulation.matches} ocorrências encontradas</span></span><ChevronRight className="h-4 w-4"/></button>)}{!center.suggestions?.length?<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Nenhuma nova automação urgente para sugerir agora.</p>:null}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-black">Atividade recente</h2><p className="text-sm text-slate-500">Tudo fica auditável.</p><div className="mt-4 grid gap-2">{(center.runs??[]).slice(0,5).map((r:any)=><div key={r.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span><b className="text-sm">{(automationByRecipe.get((center.automations??[]).find((a:any)=>a.id===r.automation_id)?.recipe_key) as any)?.name??'Automação'}</b><span className="block text-xs text-slate-400">{time(r.started_at)}</span></span><span className="text-xs font-bold text-slate-500">{r.matched_count} encontrado(s)</span></div>)}{!center.runs?.length?<p className="text-sm text-slate-400">Nenhuma execução registrada ainda.</p>:null}</div></div></section></>:null}
   {view==='mine'?<section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-black">Minhas automações</h1><p className="text-sm text-slate-500">Pausar não apaga configuração nem histórico.</p></div><button onClick={()=>setView('discover')} className="min-h-10 rounded-xl bg-blue-700 px-4 text-sm font-bold text-white">+ Adicionar automação</button></div><div className="mt-5 grid gap-3">{(center.automations??[]).map((a:any)=>{const item=(center.catalogue??[]).find((x:any)=>x.key===a.recipe_key);return <div key={a.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${statusClass(a.status)}`}>{a.status==='active'?'ATIVA':'PAUSADA'}</span><h3 className="mt-3 font-black">{a.name}</h3><p className="mt-1 text-sm text-slate-500">{item?.shortDescription}</p><p className="mt-2 text-xs text-slate-400">Modo: {modeLabel[a.mode]??a.mode} · última execução: {time(a.last_run_at)}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>item&&openRecipe(item)} className="min-h-10 rounded-xl border px-3 text-sm font-bold"><Settings2 className="mr-1 inline h-4 w-4"/>Editar</button><button disabled={busy===`run:${a.id}`||a.status!=='active'} onClick={()=>void run(a)} className="min-h-10 rounded-xl border px-3 text-sm font-bold disabled:opacity-40">{busy===`run:${a.id}`?<LoaderCircle className="mr-1 inline h-4 w-4 animate-spin"/>:<Play className="mr-1 inline h-4 w-4"/>}Executar agora</button><button disabled={busy===`toggle:${a.id}`} onClick={()=>void toggle(a)} className="min-h-10 rounded-xl border px-3 text-sm font-bold">{a.status==='active'?<Pause className="mr-1 inline h-4 w-4"/>:<Play className="mr-1 inline h-4 w-4"/>}{a.status==='active'?'Pausar':'Ativar'}</button></div></div></div>})}{!center.automations?.length?<div className="rounded-2xl bg-slate-50 p-8 text-center"><Bot className="mx-auto h-8 w-8 text-slate-400"/><b className="mt-3 block">Nenhuma automação ativa ainda</b><button onClick={()=>setView('discover')} className="mt-3 text-sm font-bold text-blue-700">Ver catálogo</button></div>:null}</div></section>:null}
   {view==='discover'?<section><div><h1 className="text-xl font-black">Descobrir automações</h1><p className="text-sm text-slate-500">Receitas prontas. Sem precisar saber programação.</p></div>{Object.entries(categoryLabel).map(([category,label])=><div key={category} className="mt-6"><h2 className="mb-3 text-sm font-black uppercase tracking-wider text-slate-500">{label}</h2><div className="grid gap-3 md:grid-cols-2">{(center.catalogue??[]).filter((x:any)=>x.category===category).map((item:any)=><button key={item.key} onClick={()=>openRecipe(item)} className="group rounded-2xl border bg-white p-5 text-left hover:border-blue-300"><div className="flex items-start justify-between"><span className="rounded-xl bg-blue-50 p-2 text-blue-700"><Wrench className="h-5 w-5"/></span>{item.automation?<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">CONFIGURADA</span>:null}</div><b className="mt-4 block">{item.title}</b><span className="mt-1 block text-sm leading-6 text-slate-500">{item.description}</span><span className="mt-3 block text-xs font-bold text-blue-700">{item.simulation.matches>0?`${item.simulation.matches} ocorrência(s) nos dados atuais`:'Configurar'} →</span></button>)}</div></div>)}</section>:null}
   {view==='suggestions'?<section className="rounded-2xl border bg-white p-5"><h1 className="text-xl font-black">Sugestões</h1><p className="text-sm text-slate-500">O BALCÃO encontra automações que fazem sentido com os dados da sua loja.</p><div className="mt-5 grid gap-3">{(center.suggestions??[]).map((item:any)=><button key={item.key} onClick={()=>openRecipe(item)} className="flex items-center justify-between rounded-2xl border p-4 text-left hover:border-blue-300"><span><b>{item.title}</b><span className="mt-1 block text-sm text-slate-500">{item.simulation.matches} ocorrência(s) · {item.simulation.critical} crítica(s)</span></span><span className="text-sm font-bold text-blue-700">Configurar →</span></button>)}{!center.suggestions?.length?<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Nenhuma sugestão nova no momento.</p>:null}</div></section>:null}
   {view==='history'?<section className="rounded-2xl border bg-white p-5"><h1 className="text-xl font-black">Histórico</h1><p className="text-sm text-slate-500">O que o BALCÃO encontrou, recomendou ou alterou.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="p-2">Quando</th><th className="p-2">Automação</th><th className="p-2">Resultado</th><th className="p-2">Ações</th><th className="p-2">Status</th></tr></thead><tbody>{(center.runs??[]).map((r:any)=>{const a=(center.automations??[]).find((x:any)=>x.id===r.automation_id);return <tr key={r.id} className="border-b"><td className="p-2">{time(r.started_at)}</td><td className="p-2 font-bold">{a?.name??'Automação'}</td><td className="p-2">{r.matched_count} encontrado(s)</td><td className="p-2">{r.action_count}</td><td className="p-2">{r.status}</td></tr>})}</tbody></table>{!center.runs?.length?<p className="p-8 text-center text-sm text-slate-400">O histórico aparecerá aqui após a primeira execução.</p>:null}</div><div className="mt-6 grid gap-2">{(center.actions??[]).slice(0,30).map((a:any)=><div key={a.id} className="rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm">{a.title}</b><span className="text-xs text-slate-400">{time(a.created_at)}</span></div><p className="mt-1 text-xs text-slate-500">{a.description}</p>{a.action_type==='price_change'?<p className="mt-1 text-xs font-bold text-blue-700">Preço alterado automaticamente e auditado.</p>:null}</div>)}</div></section>:null}
   {view==='technical'?<div className="grid gap-5"><section className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex gap-3"><KeyRound className="h-6 w-6 text-blue-300"/><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Integrações e API</p><h1 className="mt-1 text-2xl font-black">Conecte o BALCÃO ao que sua empresa já usa</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">ERP, PDV, Excel, Power BI, API e webhooks. Nada nesta área movimenta dinheiro ou envia Pix.</p></div></div></section><IntegrationsPanel storeId={storeId}/><ExportsPanel storeId={storeId}/><ApiKeysPanel storeId={storeId}/><WebhooksPanel storeId={storeId}/><IntegrationLogsPanel storeId={storeId}/></div>:null}
  </main>
  {selected?<div className="fixed inset-0 z-[120] flex items-end justify-center bg-slate-950/45 p-0 sm:items-center sm:p-6" onMouseDown={(e)=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-wider text-blue-700">{categoryLabel[selected.category]}</span><h2 className="mt-1 text-2xl font-black">{selected.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{selected.description}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold">Fechar</button></div><div className="mt-5"><b className="text-sm">Como o BALCÃO deve agir?</b><div className="mt-2 grid gap-2 sm:grid-cols-3">{['notify','recommend',...(selected.supportsAutomatic?['automatic']:[])].map(mode=><button key={mode} onClick={()=>setDraftMode(mode)} className={`rounded-xl border p-3 text-left text-sm font-bold ${draftMode===mode?'border-blue-500 bg-blue-50 text-blue-800':''}`}>{modeLabel[mode]}</button>)}</div></div>{Object.keys(draftConfig).length?<div className="mt-5"><b className="text-sm">Limites</b><div className="mt-2 grid gap-3 sm:grid-cols-2">{Object.entries(draftConfig).filter(([,value])=>typeof value==='number').map(([key,value])=><label key={key} className="text-xs font-bold text-slate-600">{configLabels[key]??key}<input type="number" value={Number(value)} onChange={e=>setDraftConfig(c=>({...c,[key]:Number(e.target.value)}))} className="mt-1 min-h-11 w-full rounded-xl border px-3 text-base font-normal text-slate-900"/></label>)}</div></div>:null}<div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-blue-700"/><b className="text-sm">Simulação com os dados atuais</b></div><p className="mt-2 text-sm text-slate-600">Esta automação encontraria <b>{selected.simulation.matches}</b> ocorrência(s), sendo <b>{selected.simulation.critical}</b> crítica(s). A simulação não altera nada.</p></div><button disabled={busy===`save:${selected.key}`} onClick={()=>void saveRecipe(selected)} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 font-black text-white disabled:opacity-50">{busy===`save:${selected.key}`?<LoaderCircle className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}{(automationByRecipe.get(selected.key) as any)?'Salvar configuração':'Ativar automação'}</button></div></div>:null}
 </div>
}
