'use client'

import { useState } from 'react'
import { Bot, Cable, ChevronRight, Download, KeyRound, Sparkles } from 'lucide-react'
import ApiKeysPanel from './automations/ApiKeysPanel'
import IntegrationsPanel from './automations/IntegrationsPanel'
import WebhooksPanel from './automations/WebhooksPanel'
import IntegrationLogsPanel from './automations/IntegrationLogsPanel'
import PricingPanel from './automations/PricingPanel'
import ExportsPanel from './automations/ExportsPanel'

type Panel='home'|'pricing'|'connect'|'exports'|'advanced'
export default function AutomationsHub({storeId,managementAccess=false}:{storeId:string;managementAccess?:boolean}){const[panel,setPanel]=useState<Panel>('home')
if(panel!=='home')return <div className="grid gap-5"><button type="button" onClick={()=>setPanel('home')} className="w-fit min-h-10 text-sm font-bold text-blue-700">← Automações</button>{panel==='pricing'?<PricingPanel storeId={storeId}/>:null}{panel==='connect'?<IntegrationsPanel storeId={storeId}/>:null}{panel==='exports'?<ExportsPanel storeId={storeId}/>:null}{panel==='advanced'?<><section className="rounded-2xl border bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Integração avançada</p><h2 className="mt-2 text-2xl font-bold">APIs, webhooks e sistemas externos</h2><p className="mt-2 max-w-3xl text-sm text-slate-300">Crie acessos mínimos, conecte sistemas e acompanhe entregas. Financeiro continua somente leitura e não existe API de Pix, pagamento ou transferência.</p></section><ApiKeysPanel storeId={storeId}/><WebhooksPanel storeId={storeId}/><IntegrationsPanel storeId={storeId}/><IntegrationLogsPanel storeId={storeId}/></>:null}<p className="text-xs text-slate-400">Loja: {storeId}{managementAccess?' · acesso de gestão':''}</p></div>
const cards=[{id:'pricing' as const,title:'Preço Inteligente',description:'Use custo, margem, estoque e vendas para receber sugestões ou ajustar preços automaticamente.',icon:Sparkles,badge:'Inteligência'},{id:'connect' as const,title:'Conectar outro sistema',description:'Continue usando seu ERP, PDV ou sistema da franquia e conecte os dados ao Balcão.',icon:Cable,badge:'Conexões de dados'},{id:'exports' as const,title:'Usar meus dados fora do Balcão',description:'Leve produtos, estoque, vendas e financeiro para Excel, Power BI ou outro sistema.',icon:Download,badge:'Dados'},{id:'advanced' as const,title:'Integração avançada',description:'Chaves de acesso, webhooks, integrações e logs para sua equipe de tecnologia.',icon:KeyRound,badge:'Avançado'}]
return <div className="grid gap-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start gap-3"><span className="rounded-xl bg-blue-50 p-3 text-blue-700"><Bot className="h-6 w-6"/></span><div><p className="text-sm font-bold uppercase tracking-widest text-blue-700">Automações</p><h1 className="mt-1 text-2xl font-bold">Faça o Balcão trabalhar junto com sua operação</h1><p className="mt-2 max-w-3xl text-slate-600">Ative inteligência, conecte outros sistemas e use seus dados onde preferir. Recursos técnicos só aparecem quando você abre a área avançada.</p></div></div></section><section className="grid gap-3 md:grid-cols-2">{cards.map(({id,title,description,icon:Icon,badge})=><button key={id} type="button" onClick={()=>setPanel(id)} className="group flex min-h-40 items-start gap-4 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:border-blue-300 hover:bg-blue-50/30"><span className="rounded-xl bg-slate-100 p-3 group-hover:bg-white"><Icon className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="text-xs font-bold uppercase tracking-wider text-slate-400">{badge}</span><b className="mt-2 block text-lg">{title}</b><span className="mt-2 block text-sm leading-6 text-slate-600">{description}</span></span><ChevronRight className="mt-2 h-5 w-5 text-slate-400"/></button>)}</section></div>}
