'use client'
import { useEffect,useState } from 'react'
import AutomationError from './AutomationError'
import { automationRequest, AutomationClientError } from '@/lib/platform/automation/client'

const scopes=[['products:read','Ler produtos'],['products:write','Alterar produtos'],['inventory:read','Ler estoque'],['inventory:write','Alterar estoque'],['sales:read','Ler vendas'],['sales:ingest','Enviar vendas'],['finance:read','Ler financeiro'],['pricing:read','Ler preços'],['pricing:write','Aplicar preços'],['webhooks:manage','Gerenciar webhooks']] as const
type KeyRow={id:string;name:string;prefix:string;scopes:string[];status:string;approvalStatus:string;lastUsedAt?:string|null;createdAt:string}
type UiError={message:string;code:string}|null

export default function ApiKeysPanel({storeId}:{storeId:string}){
  const[keyRows,setKeyRows]=useState<KeyRow[]>([]),[name,setName]=useState(''),[selected,setSelected]=useState<string[]>(['products:read','inventory:read','sales:read']),[secret,setSecret]=useState(''),[error,setError]=useState<UiError>(null),[busy,setBusy]=useState(false)
  async function load(){try{const p=await automationRequest<{keys:KeyRow[]}>(`/api/balcao/automations/api-keys?storeId=${encodeURIComponent(storeId)}`,undefined,'AUT-KEY-LOAD');setKeyRows(p.keys??[]);setError(null)}catch(e){const x=e as AutomationClientError;setError({message:x.message,code:x.code})}}
  useEffect(()=>{void load()},[storeId])
  async function create(){if(!name.trim()||!selected.length)return;setBusy(true);setError(null);try{const p=await automationRequest<any>('/api/balcao/automations/api-keys',{method:'POST',body:JSON.stringify({storeId,name,scopes:selected})},'AUT-KEY-CREATE');setSecret(p.secret);setName('');await load()}catch(e){const x=e as AutomationClientError;setError({message:x.message,code:x.code})}finally{setBusy(false)}}
  async function action(id:string,kind:'revoke'|'rotate'|'approve'){if(kind==='revoke'&&!confirm('Revogar esta chave?'))return;setError(null);try{const suffix=`?storeId=${encodeURIComponent(storeId)}`;const url=kind==='rotate'?`/api/balcao/automations/api-keys/${id}/rotate${suffix}`:`/api/balcao/automations/api-keys/${id}${suffix}`;const p=await automationRequest<any>(url,{method:kind==='revoke'?'DELETE':kind==='approve'?'PATCH':'POST',...(kind==='approve'?{body:JSON.stringify({approvalStatus:'approved'})}:{})},'AUT-KEY-ACTION');if(p.secret)setSecret(p.secret);await load()}catch(e){const x=e as AutomationClientError;setError({message:x.message,code:x.code})}}
  return <section className="rounded-2xl border bg-white p-5"><h3 className="text-lg font-bold">Chaves de acesso</h3><p className="mt-1 text-sm text-slate-500">Cada sistema recebe só as permissões necessárias. A chave completa aparece uma única vez.</p>{secret?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><b>Salve esta chave agora</b><code className="mt-2 block break-all rounded bg-white p-3 text-xs">{secret}</code><button onClick={()=>navigator.clipboard?.writeText(secret)} className="mt-2 min-h-10 rounded-lg border bg-white px-3 text-sm font-bold">Copiar</button><button onClick={()=>setSecret('')} className="ml-2 min-h-10 px-3 text-sm font-bold">Já salvei</button></div>:null}{error?<div className="mt-4"><AutomationError message={error.message} code={error.code} onRetry={()=>void load()}/></div>:null}<div className="mt-4 rounded-xl bg-slate-50 p-4"><label className="text-sm font-bold">Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Power BI da loja" className="mt-2 min-h-11 w-full rounded-lg border bg-white px-3"/></label><div className="mt-3 grid gap-2 sm:grid-cols-2">{scopes.map(([value,label])=><label key={value} className="flex items-center gap-2 rounded-lg border bg-white p-3 text-sm"><input type="checkbox" checked={selected.includes(value)} onChange={()=>setSelected(c=>c.includes(value)?c.filter(x=>x!==value):[...c,value])}/><span>{label}</span></label>)}</div><button disabled={busy||!name.trim()||!selected.length} onClick={()=>void create()} className="mt-4 min-h-11 rounded-xl bg-blue-700 px-4 font-bold text-white disabled:opacity-40">{busy?'Criando…':'Criar chave'}</button></div><div className="mt-5 grid gap-2">{keyRows.map(k=><div key={k.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>{k.name}</b><p className="text-xs text-slate-500">rpg_live_{k.prefix}_•••• · {k.status}{k.approvalStatus==='pending'?' · aguardando aprovação':''}</p></div><div className="flex flex-wrap gap-2">{k.approvalStatus==='pending'?<button onClick={()=>void action(k.id,'approve')} className="min-h-9 rounded-lg border px-3 text-xs font-bold">Aprovar</button>:null}<button onClick={()=>void action(k.id,'rotate')} className="min-h-9 rounded-lg border px-3 text-xs font-bold">Rotacionar</button>{k.status==='active'?<button onClick={()=>void action(k.id,'revoke')} className="min-h-9 rounded-lg border px-3 text-xs font-bold text-red-700">Revogar</button>:null}</div></div><p className="mt-2 text-xs text-slate-500">{k.scopes.join(' · ')}</p></div>)}{!keyRows.length?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma chave criada ainda.</p>:null}</div></section>
}
