'use client'
import { useEffect,useState } from 'react'
const money=(c:number)=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function PricingPanel({storeId}:{storeId:string}){const[settings,setSettings]=useState<any>(null);const[recommendations,setRecommendations]=useState<any[]>([]);const[busy,setBusy]=useState('');const[error,setError]=useState('')
async function load(){const r=await fetch(`/api/balcao/automations/pricing?storeId=${encodeURIComponent(storeId)}`,{cache:'no-store'});const p=await r.json().catch(()=>({}));if(r.ok){setSettings(p.settings);setRecommendations(p.recommendations??[])}else setError(p.error??'Falha ao analisar preços.')}useEffect(()=>{void load()},[storeId])
async function mode(next:string){setBusy('mode');const r=await fetch('/api/balcao/automations/pricing',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({storeId,mode:next,minimumMarginBps:settings?.minimum_margin_bps??2500,targetMarginBps:settings?.target_margin_bps??3000,maxChangeBps:settings?.max_change_bps??500,minimumIntervalDays:settings?.minimum_interval_days??7,minimumSalesCount:settings?.minimum_sales_count??20})});const p=await r.json().catch(()=>({}));if(r.ok)setSettings(p.settings);else setError(p.error??'Falha ao salvar.');setBusy('')}
async function apply(productId:string){setBusy(productId);const r=await fetch(`/api/balcao/automations/pricing/${productId}/apply`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storeId})});const p=await r.json().catch(()=>({}));if(!r.ok)setError(p.error??'Falha ao aplicar preço.');await load();setBusy('')}
if(!settings)return <p className="p-4 text-sm text-slate-500">Analisando preços…</p>
return <div className="grid gap-5"><section className="rounded-2xl border p-5"><h3 className="text-lg font-bold">Preço Inteligente</h3><p className="mt-1 text-sm text-slate-500">O Balcão usa margem, custo, giro e dias de estoque. Nenhum dado regional é usado nesta fase.</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{[['off','Desligado','Só você altera preços.'],['recommend','Apenas recomendar','Balcão analisa e você aprova.'],['automatic','Automático','Política pronta para automação com limites.']].map(([value,title,desc])=><button key={value} disabled={busy==='mode'} onClick={()=>mode(value)} className={`rounded-xl border p-4 text-left ${settings.mode===value?'border-blue-500 bg-blue-50':''}`}><b>{title}</b><span className="mt-1 block text-xs text-slate-500">{desc}</span></button>)}</div><p className="mt-3 text-xs text-slate-400">Limites padrão: margem mínima {(settings.minimum_margin_bps/100).toFixed(0)}% · variação máxima {(settings.max_change_bps/100).toFixed(0)}% · intervalo mínimo {settings.minimum_interval_days} dias. O modo automático fica sujeito a confiança e guardrails do motor.</p></section>{error?<p className="text-sm font-bold text-red-700">{error}</p>:null}<section className="rounded-2xl border p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold">Recomendações</h3><p className="text-sm text-slate-500">{recommendations.filter(r=>r.action!=='keep').length} produtos merecem atenção.</p></div></div><div className="mt-4 grid gap-2">{recommendations.filter(r=>r.action!=='keep').slice(0,50).map(r=><div key={r.productId} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><b>{r.productName}</b><p className="mt-1 text-xs text-slate-500">{money(r.currentPriceCents)} → <b className="text-slate-800">{money(r.recommendedPriceCents)}</b> · margem {r.grossMarginPct.toFixed(1)}% → {r.expectedGrossMarginPct.toFixed(1)}% · confiança {r.confidence}</p><p className="mt-1 text-xs text-slate-400">{r.reasons.join(' · ')}{r.daysOfInventory!=null?` · ${r.daysOfInventory} dias de estoque`:''}</p></div>{settings.mode!=='off'?<button disabled={busy===r.productId} onClick={()=>apply(r.productId)} className="min-h-10 rounded-lg bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-40">{busy===r.productId?'Aplicando…':`Aplicar ${money(r.recommendedPriceCents)}`}</button>:null}</div>)}{!recommendations.some(r=>r.action!=='keep')?<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">Nenhum preço precisa de atenção com os dados atuais.</p>:null}</div></section></div>}
