'use client'
import { useEffect,useState } from 'react'
const events=['sale.created','product.created','product.updated','inventory.movement.created','inventory.low_stock','pricing.recommendation.created','pricing.price.changed','finance.transaction.created','finance.card_settlement.detected','integration.sync.completed','integration.sync.failed']
type Hook={id:string;name:string;url:string;event_types:string[];status:string;consecutive_failures:number;last_success_at?:string|null}
export default function WebhooksPanel({storeId}:{storeId:string}){const[list,setList]=useState<Hook[]>([]);const[name,setName]=useState('');const[url,setUrl]=useState('');const[selected,setSelected]=useState<string[]>(['sale.created']);const[secret,setSecret]=useState('');const[error,setError]=useState('')
async function load(){const r=await fetch(`/api/balcao/automations/webhooks?storeId=${encodeURIComponent(storeId)}`,{cache:'no-store'});const p=await r.json().catch(()=>({}));if(r.ok)setList(p.webhooks??[]);else setError(p.error??'Falha ao carregar webhooks.')}useEffect(()=>{void load()},[storeId])
async function create(){const r=await fetch('/api/balcao/automations/webhooks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storeId,name,url,eventTypes:selected})});const p=await r.json().catch(()=>({}));if(!r.ok)return setError(p.error??'Não foi possível criar.');setSecret(p.secret);setName('');setUrl('');await load()}
async function act(h:Hook,kind:'test'|'rotate'|'delete'|'toggle'){const endpoint=kind==='rotate'?`/api/balcao/automations/webhooks/${h.id}/rotate`:kind==='test'?`/api/balcao/automations/webhooks/${h.id}/test`:`/api/balcao/automations/webhooks/${h.id}`;const method=kind==='delete'?'DELETE':kind==='toggle'?'PATCH':'POST';const r=await fetch(endpoint,{method,headers:{'content-type':'application/json'},...(kind==='toggle'?{body:JSON.stringify({status:h.status==='active'?'paused':'active'})}:{})});const p=await r.json().catch(()=>({}));if(!r.ok)return setError(p.error??`Falha: ${r.status}`);if(p.secret)setSecret(p.secret);await load()}
return <section className="rounded-2xl border p-5"><h3 className="text-lg font-bold">Webhooks</h3><p className="mt-1 text-sm text-slate-500">O Balcão avisa seu sistema quando algo acontece. As entregas são assinadas e não travam Caixa ou Estoque.</p>{secret?<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><b>Segredo do webhook — salve agora</b><code className="mt-2 block break-all rounded bg-white p-3 text-xs">{secret}</code><button onClick={()=>navigator.clipboard?.writeText(secret)} className="mt-2 min-h-9 rounded border bg-white px-3 text-xs font-bold">Copiar</button><button onClick={()=>setSecret('')} className="ml-2 text-xs font-bold">Já salvei</button></div>:null}{error?<p className="mt-3 text-sm font-bold text-red-700">{error}</p>:null}<div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Nome<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border bg-white px-3" placeholder="Ex.: ERP central"/></label><label className="text-sm font-bold">URL HTTPS<input value={url} onChange={e=>setUrl(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border bg-white px-3" placeholder="https://..."/></label></div><details className="mt-3"><summary className="cursor-pointer text-sm font-bold">Eventos ({selected.length})</summary><div className="mt-2 grid gap-2 sm:grid-cols-2">{events.map(e=><label key={e} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={selected.includes(e)} onChange={()=>setSelected(c=>c.includes(e)?c.filter(x=>x!==e):[...c,e])}/>{e}</label>)}</div></details><button disabled={!name.trim()||!url.trim()||!selected.length} onClick={create} className="mt-4 min-h-10 rounded-lg bg-blue-700 px-4 text-sm font-bold text-white disabled:opacity-40">Criar webhook</button></div><div className="mt-5 grid gap-2">{list.map(h=><div key={h.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div className="min-w-0"><b>{h.name}</b><p className="truncate text-xs text-slate-500">{h.url}</p><p className="mt-1 text-xs text-slate-500">{h.status} · falhas seguidas: {h.consecutive_failures}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>act(h,'test')} className="min-h-9 rounded border px-3 text-xs font-bold">Testar</button><button onClick={()=>act(h,'toggle')} className="min-h-9 rounded border px-3 text-xs font-bold">{h.status==='active'?'Pausar':'Ativar'}</button><button onClick={()=>act(h,'rotate')} className="min-h-9 rounded border px-3 text-xs font-bold">Novo segredo</button><button onClick={()=>act(h,'delete')} className="min-h-9 rounded border px-3 text-xs font-bold text-red-700">Excluir</button></div></div><p className="mt-2 break-words text-[11px] text-slate-400">{h.event_types.join(' · ')}</p></div>)}</div></section>}
