create table if not exists public.web_analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_key uuid not null,
  visitor_key uuid not null,
  event_type text not null check (event_type in (
    'page_view','click','pointer','scroll','heartbeat','performance',
    'form_start','form_submit_attempt','form_submit_success'
  )),
  path text not null,
  source text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  device_type text,
  browser text,
  os text,
  viewport_width integer,
  viewport_height integer,
  screen_width integer,
  screen_height integer,
  language text,
  timezone text,
  country text,
  region text,
  city text,
  section text,
  target text,
  x_ratio real check (x_ratio is null or (x_ratio >= 0 and x_ratio <= 1)),
  y_ratio real check (y_ratio is null or (y_ratio >= 0 and y_ratio <= 1)),
  scroll_ratio real check (scroll_ratio is null or (scroll_ratio >= 0 and scroll_ratio <= 1)),
  value numeric,
  meta jsonb not null default '{}'::jsonb
);

create index if not exists web_analytics_events_created_idx on public.web_analytics_events (created_at desc);
create index if not exists web_analytics_events_session_idx on public.web_analytics_events (session_key, created_at);
create index if not exists web_analytics_events_visitor_idx on public.web_analytics_events (visitor_key, created_at);
create index if not exists web_analytics_events_type_idx on public.web_analytics_events (event_type, created_at);
create index if not exists web_analytics_events_path_idx on public.web_analytics_events (path, created_at);

comment on table public.web_analytics_events is
  'Analitica first-party do site publico RPG. Nao armazena conteudo digitado, senha, CPF ou IP bruto.';

alter table public.web_analytics_events enable row level security;
revoke all on table public.web_analytics_events from anon, authenticated;
grant select, insert, update, delete on table public.web_analytics_events to service_role;
grant usage, select on sequence public.web_analytics_events_id_seq to service_role;
