import { randomUUID } from 'node:crypto'
import { createAdminClient } from '@/lib/supabase/admin'
import { loadInventoryState, saveInventoryState } from '../inventoryAdapter'
import { normalizeAuthority } from './authority'
import { resolveMapping, upsertMapping } from './entityMappings'
import { emitPlatformEvent } from '../events/outbox'

const MAX_RECORDS=500
function records(value:unknown){ if(!Array.isArray(value)||value.length<1||value.length>MAX_RECORDS) throw new Error('BALCAO_IMPORT_SIZE'); return value as any[] }
async function assertAuthority(input:{integrationId?:string;businessId:string;storeId:string;domain:'products'|'inventory'|'sales'}){ if(!input.integrationId) return; const {data}=await createAdminClient().from('balcao_integration_connections').select('business_id,store_id,authority,status').eq('id',input.integrationId).maybeSingle(); if(!data||data.status!=='active'||String(data.business_id)!==input.businessId||(data.store_id&&String(data.store_id)!==input.storeId)) throw new Error('BALCAO_INTEGRATION_FORBIDDEN'); const authority=normalizeAuthority(data.authority); const allowed=input.domain==='products'?['external','merge'].includes(authority.products):authority[input.domain]==='external'; if(!allowed) throw new Error('BALCAO_SOURCE_OF_TRUTH') }

export async function ingestProducts(input:{businessId:string;storeId:string;integrationId?:string;records:unknown}){ await assertAuthority({...input,domain:'products'}); const batch=records(input.records); const state=await loadInventoryState(input.storeId,input.businessId); const results:any[]=[]; const events:any[]=[]; for(const row of batch){ const externalId=String(row.externalId??'').trim(); const barcode=String(row.barcode??'').trim(); const name=String(row.name??'').trim(); if(!externalId||!barcode||!name) throw new Error('BALCAO_IMPORT_PRODUCT_INVALID'); let internalId=input.integrationId?await resolveMapping(input.integrationId,'product',externalId):null; let index=internalId?state.products.findIndex((p:any)=>String(p.id)===internalId):-1; if(index<0) index=state.products.findIndex((p:any)=>String(p.barcode)===barcode); const created=index<0; const previous=created?null:state.products[index]; const product={...(previous??{}),id:previous?.id??randomUUID(),barcode,name,unit:row.unit==='KG'?'KG':'UN',priceCents:Number.isFinite(Number(row.priceCents))?Math.max(0,Math.round(Number(row.priceCents))):Number(previous?.priceCents??0),averageCostCents:Number.isFinite(Number(row.averageCostCents))?Math.max(0,Math.round(Number(row.averageCostCents))):Number(previous?.averageCostCents??0),stockMilli:Number.isFinite(Number(row.stockMilli))?Math.max(0,Math.round(Number(row.stockMilli))):Number(previous?.stockMilli??0),minStockMilli:Number.isFinite(Number(row.minStockMilli))?Math.max(0,Math.round(Number(row.minStockMilli))):Number(previous?.minStockMilli??0),catalogBrand:row.brand??previous?.catalogBrand,catalogImageUrl:row.imageUrl??previous?.catalogImageUrl}; if(created) state.products.push(product); else state.products[index]=product; if(input.integrationId) await upsertMapping({integrationId:input.integrationId,businessId:input.businessId,storeId:input.storeId,entityType:'product',externalId,internalId:String(product.id),provenance:{source:'public_api'}}); results.push({externalId,id:String(product.id),status:created?'created':'updated'}); events.push({type:created?'product.created':'product.updated',id:String(product.id),data:{productId:String(product.id),externalId}}) }
 await saveInventoryState(input.storeId,input.businessId,state); for(const event of events) await emitPlatformEvent({businessId:input.businessId,storeId:input.storeId,type:event.type,aggregateType:'product',aggregateId:event.id,data:event.data}); return results }

export async function ingestSales(input:{businessId:string;storeId:string;integrationId?:string;records:unknown}){ await assertAuthority({...input,domain:'sales'}); const batch=records(input.records); const state=await loadInventoryState(input.storeId,input.businessId); const results:any[]=[]; const events:any[]=[]; for(const row of batch){ const externalId=String(row.externalId??'').trim(); if(!externalId||!Array.isArray(row.items)||!row.items.length) throw new Error('BALCAO_IMPORT_SALE_INVALID'); const mapped=input.integrationId?await resolveMapping(input.integrationId,'sale',externalId):null; if(mapped||state.sales.some((s:any)=>String(s.externalId??'')===externalId)){ results.push({externalId,id:mapped??externalId,status:'existing'}); continue } const items=row.items.map((item:any)=>({productId:String(item.productId),quantityMilli:Math.max(1,Math.round(Number(item.quantityMilli??0))),unitPriceCents:Math.max(0,Math.round(Number(item.unitPriceCents??0))),lineTotalCents:Math.max(0,Math.round(Number(item.lineTotalCents??Number(item.unitPriceCents??0)*Number(item.quantityMilli??0)/1000))),unitCostCents:Math.max(0,Math.round(Number(item.unitCostCents??0))),lineCostCents:Math.max(0,Math.round(Number(item.lineCostCents??Number(item.unitCostCents??0)*Number(item.quantityMilli??0)/1000)))})); const total=Number.isFinite(Number(row.totalCents))?Math.round(Number(row.totalCents)):items.reduce((sum:number,item:any)=>sum+item.lineTotalCents,0); const cogs=items.reduce((sum:number,item:any)=>sum+item.lineCostCents,0); const id=randomUUID(); const sale={id,externalId,createdAt:row.createdAt&&Number.isFinite(new Date(row.createdAt).getTime())?new Date(row.createdAt).toISOString():new Date().toISOString(),totalCents:total,cogsCents:cogs,grossProfitCents:total-cogs,items,...(row.paymentMethod&&['pix','card','cash'].includes(row.paymentMethod)?{payment:{method:row.paymentMethod,confirmedAt:row.confirmedAt??row.createdAt??new Date().toISOString()}}:{})}; state.sales.unshift(sale); if(input.integrationId) await upsertMapping({integrationId:input.integrationId,businessId:input.businessId,storeId:input.storeId,entityType:'sale',externalId,internalId:id,provenance:{source:'public_api'}}); results.push({externalId,id,status:'created'}); events.push({id,data:{saleId:id,externalId,totalCents:total}}) }
 await saveInventoryState(input.storeId,input.businessId,state); for(const event of events) await emitPlatformEvent({businessId:input.businessId,storeId:input.storeId,type:'sale.created',aggregateType:'sale',aggregateId:event.id,data:event.data}); return results }

export async function ingestInventoryMovements(input:{businessId:string;storeId:string;integrationId?:string;records:unknown}){ await assertAuthority({...input,domain:'inventory'}); const batch=records(input.records); const state=await loadInventoryState(input.storeId,input.businessId); const results:any[]=[]; const events:any[]=[]; for(const row of batch){ const externalId=String(row.externalId??'').trim(); if(!externalId) throw new Error('BALCAO_IMPORT_MOVEMENT_INVALID'); const mapped=input.integrationId?await resolveMapping(input.integrationId,'inventory_movement',externalId):null; if(mapped){ results.push({externalId,id:mapped,status:'existing'}); continue } let productId=String(row.productId??''); if(!productId&&input.integrationId&&row.productExternalId) productId=(await resolveMapping(input.integrationId,'product',String(row.productExternalId)))??''; const productIndex=state.products.findIndex((p:any)=>String(p.id)===productId); const delta=Math.round(Number(row.quantityDeltaMilli??0)); if(productIndex<0||!Number.isFinite(delta)||delta===0) throw new Error('BALCAO_IMPORT_MOVEMENT_INVALID'); const nextStock=Number(state.products[productIndex].stockMilli??0)+delta; if(nextStock<0) throw new Error('BALCAO_IMPORT_NEGATIVE_STOCK'); state.products[productIndex]={...state.products[productIndex],stockMilli:nextStock}; const id=randomUUID(); state.movements.push({id,productId,type:row.type==='purchase'?'purchase':'adjustment',quantityMilli:delta,createdAt:row.createdAt&&Number.isFinite(new Date(row.createdAt).getTime())?new Date(row.createdAt).toISOString():new Date().toISOString(),note:String(row.note??'Importação por integração')}); if(input.integrationId) await upsertMapping({integrationId:input.integrationId,businessId:input.businessId,storeId:input.storeId,entityType:'inventory_movement',externalId,internalId:id,provenance:{source:'public_api'}}); results.push({externalId,id,status:'created'}); events.push({id,productId,delta,nextStock,minStock:Number(state.products[productIndex].minStockMilli??0)}) }
 await saveInventoryState(input.storeId,input.businessId,state); for(const event of events){ await emitPlatformEvent({businessId:input.businessId,storeId:input.storeId,type:'inventory.movement.created',aggregateType:'inventory_movement',aggregateId:event.id,data:{movementId:event.id,productId:event.productId,quantityDeltaMilli:event.delta}}); if(event.nextStock<=event.minStock) await emitPlatformEvent({businessId:input.businessId,storeId:input.storeId,type:'inventory.low_stock',aggregateType:'product',aggregateId:event.productId,data:{productId:event.productId,stockMilli:event.nextStock,minStockMilli:event.minStock}}) } return results }
